name: React travel site deploymet

on:
  push:
    branches: 
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm ci

      - name: Update Browserslist
        run: npx update-browserslist-db@latest

      - name: Build packages
        run: |
          export CI=false
          npm run build




        
    
